language: node_js
node_js:
  - "10"

os:
  - linux
dist: trusty # to use Ubuntu 14.04

# temporary fix to prevent an issue related to chrome headless. I should restore this to false as soon as possible.
# also I should remove these 2 commands from before_script
# 1. sudo chown root /opt/google/chrome/chrome-sandbox
# 2. sudo chmod 4755 /opt/google/chrome/chrome-sandbox
sudo: true

git:
  depth: 3

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8

matrix:
  fast_finish: true

before_install:
  - source travisci/before_install.sh
install:
  - bash travisci/install.sh
after_install:
  - npm rebuild node-sass
before_script:
  - source travisci/before_script.sh # starts in the same shell
script:
  - bash travisci/script.sh
#after_success:
#  - source travisci/after_success.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

cache:
  apt: true
  bundler: true
  directories:
    - ./node_modules
    - '$HOME/.sonar/cache'
