version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10-stretch-browsers # to use the latest version switch to node:latest-browsers
      # Environment variable for all commands executed in the primary container
        environment:
          NODE_ENV: test
          CI: yes
    steps:
      - checkout
      - run:
          name: npm-install-npm-latest
          command: sudo npm install -g npm@6.8.0
      - run:
          name: npm-install-global
          command: sudo npm install -g @angular/cli@8.0.4
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: node-sass-clean
          command: npm rebuild node-sass --force
#      - run:
#          name: init-codeclimate-test-reporter
#          command: |
#            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#            chmod +x ./cc-test-reporter
#            ./cc-test-reporter before-build
      - run:
          name: npm-install
          command: npm ci
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release
            sudo apt-get install libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      # prepare
      - run:
          name: run-clean-all
          command: npm run clean:all

      # build the library and copy it in all examples
      - run:
          name: run-build-all-libray
          command: npm run build:all
      # main angular-cli
      - run:
          name: run-build-dev-main-angular-cli
          command: npm run build:main:dev
      - run:
          name: run-build-prod-main-angular-cli
          command: npm run build:main:prod
      # test the library
      - run:
          name: run-test-library
          command: npm run test:ci
      - run:
          name: run-e2e-library
          command: npm run e2e:ci
